"""
MovieLens Recommendation System - Streamlit Application
Main entry point for the web application

This app connects to the notebook by:
1. Loading trained models from models/ directory (saved by notebook)
2. Loading data from outputs/ directory (generated by notebook)
3. Using the same data processing logic from the notebook
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os
from pathlib import Path
import warnings
from sklearn.preprocessing import MultiLabelBinarizer, StandardScaler
from sklearn.neighbors import NearestNeighbors
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score
warnings.filterwarnings('ignore')

# Define model classes (required for joblib to load saved models)
class NonPersonalizedRecommender:
    """
    Non-personalized recommendation system based on popularity and IMDB weighted score
    Formula: WR = (v/(v+m)) * R + (m/(v+m)) * C
    """
    
    def __init__(self, min_ratings: int = 50, percentile: int = 90):
        self.min_ratings = min_ratings
        self.percentile = percentile
        self.movie_scores = None
        
    def fit(self, ratings_df: pd.DataFrame, movies_df: pd.DataFrame):
        """Calculate IMDB weighted scores for all movies"""
        # Calculate statistics
        movie_stats = ratings_df.groupby('movieId').agg({
            'rating': ['mean', 'count']
        }).reset_index()
        
        movie_stats.columns = ['movieId', 'avg_rating', 'num_ratings']
        
        # Calculate C (mean rating across all movies)
        C = ratings_df['rating'].mean()
        
        # Calculate m (minimum votes required) based on percentile
        m = movie_stats['num_ratings'].quantile(self.percentile / 100)
        
        # Calculate weighted score
        movie_stats['weighted_score'] = (
            (movie_stats['num_ratings'] / (movie_stats['num_ratings'] + m)) * movie_stats['avg_rating'] +
            (m / (movie_stats['num_ratings'] + m)) * C
        )
        
        # Merge with movie details
        self.movie_scores = movie_stats.merge(
            movies_df[['movieId', 'title', 'genres', 'release_year']], 
            on='movieId'
        )
        
        # Sort by weighted score
        self.movie_scores = self.movie_scores.sort_values('weighted_score', ascending=False)
        
        return self
    
    def recommend(self, n: int = 10, genre: str = None) -> pd.DataFrame:
        """Get top N recommendations"""
        df = self.movie_scores.copy()
        
        # Filter by genre if specified
        if genre:
            df = df[df['genres'].str.contains(genre, case=False, na=False)]
        
        return df.head(n)[['movieId', 'title', 'genres', 'avg_rating', 
                          'num_ratings', 'weighted_score']]

class ContentBasedRecommender:
    """
    Content-based recommendation system using movie features
    """
    
    def __init__(self, model_type: str = 'random_forest'):
        self.model_type = model_type
        self.model = None
        self.scaler = StandardScaler()
        self.mlb = MultiLabelBinarizer()
        self.feature_names = None
        self.movies_df = None
        self.ratings_df = None  # Store for find_similar_movies
        
    def _prepare_features(self, ratings_df: pd.DataFrame, movies_df: pd.DataFrame) -> tuple:
        """Prepare feature matrix"""
        # Merge ratings with movies
        df = ratings_df.merge(movies_df[['movieId', 'genres_list', 'release_year', 'genre_count']], 
                             on='movieId')
        
        # Calculate movie statistics
        movie_stats = df.groupby('movieId').agg({
            'rating': ['mean', 'std', 'count']
        }).reset_index()
        
        movie_stats.columns = ['movieId', 'movie_avg_rating', 'movie_std_rating', 'movie_num_ratings']
        
        df = df.merge(movie_stats, on='movieId')
        
        # One-hot encode genres
        genre_encoded = self.mlb.fit_transform(df['genres_list'])
        genre_df = pd.DataFrame(
            genre_encoded, 
            columns=[f'genre_{g}' for g in self.mlb.classes_],
            index=df.index
        )
        
        # Combine features
        feature_df = pd.concat([
            df[['release_year', 'genre_count', 'movie_avg_rating', 'movie_std_rating', 'movie_num_ratings']].fillna(0),
            genre_df
        ], axis=1)
        
        self.feature_names = feature_df.columns.tolist()
        
        return feature_df, df['rating']
    
    def fit(self, ratings_df: pd.DataFrame, movies_df: pd.DataFrame):
        """Train the content-based model"""
        self.movies_df = movies_df
        self.ratings_df = ratings_df
        
        # Prepare features
        X, y = self._prepare_features(ratings_df, movies_df)
        
        # Split data
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )
        
        # Scale features
        X_train_scaled = self.scaler.fit_transform(X_train)
        X_test_scaled = self.scaler.transform(X_test)
        
        # Train model
        if self.model_type == 'knn':
            self.model = NearestNeighbors(n_neighbors=10, metric='cosine')
            self.model.fit(X_train_scaled)
            predictions = np.full(len(X_test), y_train.mean())
        elif self.model_type == 'random_forest':
            self.model = RandomForestRegressor(n_estimators=100, max_depth=10, 
                                              random_state=42, n_jobs=-1)
            self.model.fit(X_train_scaled, y_train)
            predictions = self.model.predict(X_test_scaled)
        elif self.model_type == 'ridge':
            self.model = Ridge(alpha=1.0)
            self.model.fit(X_train_scaled, y_train)
            predictions = self.model.predict(X_test_scaled)
        else:
            raise ValueError(f"Unknown model type: {self.model_type}")
        
        # Calculate metrics
        rmse = np.sqrt(mean_squared_error(y_test, predictions))
        mae = mean_absolute_error(y_test, predictions)
        
        # Calculate accuracy for binary classification (rating >= 3.5)
        y_test_binary = (y_test >= 3.5).astype(int)
        pred_binary = (predictions >= 3.5).astype(int)
        accuracy = accuracy_score(y_test_binary, pred_binary)
        
        return {'rmse': rmse, 'mae': mae, 'accuracy': accuracy}
    
    def find_similar_movies(self, movie_id: int, n: int = 10) -> pd.DataFrame:
        """Find similar movies based on content features"""
        if self.movies_df is None:
            raise ValueError("Model not trained yet")
        
        movie_row = self.movies_df[self.movies_df['movieId'] == movie_id]
        if len(movie_row) == 0:
            raise ValueError(f"Movie ID {movie_id} not found")
        
        # Calculate movie statistics from ratings
        if self.ratings_df is not None:
            movie_stats = self.ratings_df.groupby('movieId').agg({
                'rating': ['mean', 'std', 'count']
            }).reset_index()
            movie_stats.columns = ['movieId', 'movie_avg_rating', 'movie_std_rating', 'movie_num_ratings']
            movie_stats_dict = movie_stats.set_index('movieId').to_dict('index')
        else:
            movie_stats_dict = {}
        
        # Prepare features for all movies
        all_features = []
        movie_ids_list = []
        
        for _, movie in self.movies_df.iterrows():
            # Get stats or defaults
            stats = movie_stats_dict.get(movie['movieId'], {})
            movie_avg = float(stats.get('movie_avg_rating', 3.5) or 3.5)
            movie_std = float(stats.get('movie_std_rating', 0.5) or 0.5)
            movie_count = float(stats.get('movie_num_ratings', 10) or 10)
            
            # Encode genres
            genre_encoded = self.mlb.transform([movie['genres_list']])[0]
            
            # Build features - convert to float and handle NaN
            release_year = movie.get('release_year', 0)
            if pd.isna(release_year):
                release_year = 0
            release_year = float(release_year or 0)
            
            genre_count = movie.get('genre_count', 0)
            if pd.isna(genre_count):
                genre_count = 0
            genre_count = float(genre_count or 0)
            
            features = [
                release_year,
                genre_count,
                movie_avg,
                movie_std,
                movie_count
            ] + genre_encoded.tolist()
            
            all_features.append(features)
            movie_ids_list.append(movie['movieId'])
        
        # Create DataFrame and ensure no NaN
        all_features_df = pd.DataFrame(all_features, columns=self.feature_names)
        all_features_df = all_features_df.fillna(0)  # Fill any remaining NaN
        
        # Scale features
        all_features_scaled = self.scaler.transform(all_features_df)
        
        # Find target movie position
        target_pos = movie_ids_list.index(movie_id)
        target_features = all_features_scaled[target_pos:target_pos+1]
        
        # Find similar movies
        if self.model_type == 'knn':
            distances, indices = self.model.kneighbors(target_features, n_neighbors=n+1)
            similar_positions = indices[0][1:]  # Exclude target
        else:
            from sklearn.metrics.pairwise import cosine_similarity
            similarities = cosine_similarity(target_features, all_features_scaled)[0]
            sorted_positions = np.argsort(similarities)[::-1]
            # Exclude target and get top n
            similar_positions = [p for p in sorted_positions if p != target_pos][:n]
        
        # Get similar movie IDs
        similar_movie_ids = [movie_ids_list[p] for p in similar_positions]
        
        # Return similar movies
        similar_movies = self.movies_df[self.movies_df['movieId'].isin(similar_movie_ids)][
            ['movieId', 'title', 'genres', 'release_year']
        ].copy()
        
        return similar_movies

# Page configuration
st.set_page_config(
    page_title="MovieLens Recommender",
    page_icon="🎬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Enhanced CSS with FontAwesome icons and modern dark theme
# Inject CSS at the very top to ensure it applies
css_injection = """
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');
    
    * {
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    }
    
    :root {
        --primary: #E50914;
        --primary-dark: #B20710;
        --secondary: #564d4d;
        --accent: #00D4FF;
        --accent-green: #46D369;
        --background: #000000;
        --surface: #141414;
        --surface-light: #1f1f1f;
        --surface-hover: #2a2a2a;
        --text-primary: #FFFFFF;
        --text-secondary: #B3B3B3;
        --text-muted: #808080;
        --border: rgba(255, 255, 255, 0.1);
        --shadow-sm: 0 2px 8px rgba(0, 0, 0, 0.3);
        --shadow-md: 0 4px 16px rgba(0, 0, 0, 0.4);
        --shadow-lg: 0 8px 32px rgba(0, 0, 0, 0.5);
        --gradient-primary: linear-gradient(135deg, #E50914 0%, #B20710 50%, #8B0000 100%);
        --gradient-secondary: linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%);
        --gradient-accent: linear-gradient(135deg, #00D4FF 0%, #0099CC 100%);
    }
    
    .stApp {
        background: var(--background);
        color: var(--text-primary);
    }
    
    .main .block-container {
        padding-top: 2rem;
        padding-bottom: 2rem;
        max-width: 1400px;
    }
    
    h1, h2, h3, h4, h5, h6 {
        color: var(--text-primary);
        font-weight: 700;
        letter-spacing: -0.02em;
    }
    
    .app-header {
        background: var(--gradient-primary);
        padding: 3rem 2rem;
        border-radius: 16px;
        margin-bottom: 3rem;
        text-align: center;
        box-shadow: var(--shadow-lg);
        position: relative;
        overflow: hidden;
    }
    
    .app-header::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background: radial-gradient(circle at 30% 50%, rgba(255, 255, 255, 0.1) 0%, transparent 50%);
        pointer-events: none;
    }
    
    .app-header h1 {
        color: white;
        font-size: 3.5rem;
        font-weight: 800;
        margin: 0;
        text-shadow: 0 4px 12px rgba(0, 0, 0, 0.5);
        position: relative;
        z-index: 1;
    }
    
    .app-header p {
        color: rgba(255, 255, 255, 0.95);
        font-size: 1.3rem;
        margin-top: 1rem;
        font-weight: 400;
        position: relative;
        z-index: 1;
    }
    
    .icon-inline {
        margin-right: 0.5rem;
        font-size: 1em;
    }
    
    .metric-container {
        background: var(--gradient-secondary);
        border-radius: 12px;
        padding: 2rem;
        border: 1px solid var(--border);
        box-shadow: var(--shadow-md);
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        height: 100%;
    }
    
    .metric-container:hover {
        transform: translateY(-4px);
        box-shadow: var(--shadow-lg);
        border-color: var(--primary);
    }
    
    .metric-value {
        font-size: 2.8rem;
        font-weight: 800;
        background: var(--gradient-primary);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        background-clip: text;
        margin: 0.5rem 0;
        line-height: 1.2;
    }
    
    .metric-label {
        font-size: 0.95rem;
        color: var(--text-secondary);
        text-transform: uppercase;
        letter-spacing: 1.5px;
        font-weight: 600;
        margin-top: 0.5rem;
    }
    
    .movie-card {
        background: var(--gradient-secondary);
        border-radius: 12px;
        padding: 1.75rem;
        margin: 1.25rem 0;
        border-left: 4px solid var(--primary);
        box-shadow: var(--shadow-sm);
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        position: relative;
        overflow: hidden;
    }
    
    .movie-card::before {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        width: 4px;
        height: 100%;
        background: var(--gradient-primary);
        transform: scaleY(0);
        transform-origin: bottom;
        transition: transform 0.3s ease;
    }
    
    .movie-card:hover {
        transform: translateX(8px) translateY(-2px);
        box-shadow: var(--shadow-md);
        border-left-color: var(--accent);
        background: var(--surface-hover);
    }
    
    .movie-card:hover::before {
        transform: scaleY(1);
    }
    
    .movie-title {
        font-size: 1.4rem;
        font-weight: 700;
        color: var(--text-primary);
        margin-bottom: 0.75rem;
        line-height: 1.3;
    }
    
    .movie-genre {
        color: var(--accent);
        font-size: 0.95rem;
        margin-bottom: 0.75rem;
        font-weight: 500;
    }
    
    .movie-rating {
        color: var(--accent-green);
        font-weight: 700;
        font-size: 1.15rem;
        margin-bottom: 0.5rem;
    }
    
    .stButton > button {
        background: var(--gradient-primary);
        color: white;
        border: none;
        border-radius: 10px;
        padding: 0.875rem 2.5rem;
        font-weight: 700;
        font-size: 1rem;
        transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
        box-shadow: var(--shadow-sm);
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }
    
    .stButton > button:hover {
        transform: translateY(-3px);
        box-shadow: var(--shadow-md);
        background: var(--primary-dark);
    }
    
    .stButton > button:active {
        transform: translateY(-1px);
    }
    
    .button-primary {
        background: var(--gradient-primary) !important;
    }
    
    .button-secondary {
        background: var(--gradient-secondary) !important;
        border: 1px solid var(--border) !important;
    }
    
    .info-box {
        background: rgba(229, 9, 20, 0.08);
        border-left: 4px solid var(--primary);
        border-radius: 10px;
        padding: 1.5rem;
        margin: 1.5rem 0;
        box-shadow: var(--shadow-sm);
        border-right: 1px solid var(--border);
        border-top: 1px solid var(--border);
        border-bottom: 1px solid var(--border);
    }
    
    .info-box strong {
        color: var(--text-primary);
        font-weight: 700;
        display: block;
        margin-bottom: 0.75rem;
        font-size: 1.1rem;
    }
    
    .info-box code {
        background: rgba(0, 0, 0, 0.3);
        padding: 0.2rem 0.5rem;
        border-radius: 4px;
        color: var(--accent);
        font-size: 0.9em;
    }
    
    .warning-box {
        background: rgba(255, 193, 7, 0.1);
        border-left: 4px solid #FFC107;
        border-radius: 10px;
        padding: 1.25rem;
        margin: 1rem 0;
        box-shadow: var(--shadow-sm);
    }
    
    .success-box {
        background: rgba(70, 211, 105, 0.1);
        border-left: 4px solid var(--accent-green);
        border-radius: 10px;
        padding: 1.25rem;
        margin: 1rem 0;
        box-shadow: var(--shadow-sm);
    }
    
    .sidebar .sidebar-content {
        background: var(--surface);
    }
    
    [data-testid="stSidebar"] {
        background: var(--surface);
        border-right: 1px solid var(--border);
    }
    
    [data-testid="stSidebar"] [data-testid="stMarkdownContainer"] {
        color: var(--text-primary);
    }
    
    .stRadio > div {
        background: var(--surface-light);
        border-radius: 10px;
        padding: 0.5rem;
    }
    
    .stRadio > div > label {
        color: var(--text-primary);
        padding: 0.75rem 1rem;
        border-radius: 8px;
        transition: all 0.2s ease;
    }
    
    .stRadio > div > label:hover {
        background: var(--surface-hover);
    }
    
    .stRadio > div > label[data-baseweb="radio"] {
        color: var(--text-primary);
    }
    
    [data-baseweb="radio"] input:checked + label {
        background: var(--gradient-primary);
        color: white;
        font-weight: 600;
    }
    
    .stSelectbox > div > div {
        background: var(--surface-light);
        border: 1px solid var(--border);
        border-radius: 8px;
    }
    
    .stTextInput > div > div > input {
        background: var(--surface-light);
        border: 1px solid var(--border);
        border-radius: 8px;
        color: var(--text-primary);
    }
    
    .stSlider > div > div {
        color: var(--primary);
    }
    
    .stTabs [data-baseweb="tab-list"] {
        background: var(--surface);
        border-bottom: 1px solid var(--border);
        gap: 0.5rem;
    }
    
    .stTabs [data-baseweb="tab"] {
        color: var(--text-secondary);
        padding: 0.75rem 1.5rem;
        border-radius: 8px 8px 0 0;
        transition: all 0.2s ease;
    }
    
    .stTabs [aria-selected="true"] {
        background: var(--surface-light);
        color: var(--text-primary);
        border-bottom: 2px solid var(--primary);
    }
    
    .stDataFrame {
        background: var(--surface-light);
        border-radius: 10px;
        overflow: hidden;
    }
    
    .stExpander {
        background: var(--surface-light);
        border: 1px solid var(--border);
        border-radius: 10px;
        margin: 1rem 0;
    }
    
    .stExpanderHeader {
        color: var(--text-primary);
        font-weight: 600;
    }
    
    .stSuccess, .stInfo, .stWarning, .stError {
        border-radius: 10px;
        padding: 1rem 1.5rem;
        border-left: 4px solid;
        box-shadow: var(--shadow-sm);
    }
    
    .stSuccess {
        background: rgba(70, 211, 105, 0.1);
        border-color: var(--accent-green);
        color: var(--accent-green);
    }
    
    .stInfo {
        background: rgba(0, 212, 255, 0.1);
        border-color: var(--accent);
        color: var(--accent);
    }
    
    .stWarning {
        background: rgba(255, 193, 7, 0.1);
        border-color: #FFC107;
        color: #FFC107;
    }
    
    .stError {
        background: rgba(229, 9, 20, 0.1);
        border-color: var(--primary);
        color: var(--primary);
    }
    
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
    
    .stSpinner > div {
        border-color: var(--primary) transparent transparent transparent;
    }
    
    hr {
        border-color: var(--border);
        margin: 2rem 0;
    }
    
    code {
        color: var(--accent);
        background: rgba(0, 0, 0, 0.3);
        padding: 0.2rem 0.5rem;
        border-radius: 4px;
    }
    
    ul, ol {
        color: var(--text-secondary);
    }
    
    li {
        margin: 0.5rem 0;
    }
    
    strong {
        color: var(--text-primary);
        font-weight: 700;
    }
    </style>
"""
st.markdown(css_injection, unsafe_allow_html=True)

# Initialize session state
if 'models_loaded' not in st.session_state:
    st.session_state.models_loaded = False
if 'data_loaded' not in st.session_state:
    st.session_state.data_loaded = False
if 'non_pers_model' not in st.session_state:
    st.session_state.non_pers_model = None
if 'content_model' not in st.session_state:
    st.session_state.content_model = None
if 'movies_df' not in st.session_state:
    st.session_state.movies_df = None
if 'hidden_gems' not in st.session_state:
    st.session_state.hidden_gems = None

@st.cache_data
def load_data():
    """Load data files - connects to notebook outputs"""
    base_path = Path(__file__).parent
    
    try:
        # Try to load from outputs (generated by notebook)
        hidden_gems_path = base_path / 'outputs' / 'hidden_gems.csv'
        if hidden_gems_path.exists():
            hidden_gems = pd.read_csv(str(hidden_gems_path))
        elif os.path.exists('outputs/hidden_gems.csv'):
            hidden_gems = pd.read_csv('outputs/hidden_gems.csv')
        else:
            hidden_gems = pd.DataFrame()
        
        # Try to load movies data
        movies_path = base_path / 'movies.csv'
        if movies_path.exists():
            movies_df = pd.read_csv(str(movies_path))
        elif (base_path / 'data' / 'movies.csv').exists():
            movies_df = pd.read_csv(str(base_path / 'data' / 'movies.csv'))
        elif os.path.exists('data/movies.csv'):
            movies_df = pd.read_csv('data/movies.csv')
        elif os.path.exists('movies.csv'):
            movies_df = pd.read_csv('movies.csv')
        else:
            movies_df = pd.DataFrame()
        
        return movies_df, hidden_gems
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return pd.DataFrame(), pd.DataFrame()

@st.cache_resource
def load_models():
    """Load trained models - connects to notebook saved models"""
    models = {}
    base_path = Path(__file__).parent
    
    # Load non-personalized model
    try:
        model_path = base_path / 'models' / 'non_personalized_model.pkl'
        if model_path.exists():
            models['non_personalized'] = joblib.load(str(model_path))
            st.success("Non-personalized model loaded successfully")
        else:
            # Try relative path as fallback
            if os.path.exists('models/non_personalized_model.pkl'):
                models['non_personalized'] = joblib.load('models/non_personalized_model.pkl')
                st.success("Non-personalized model loaded successfully")
            else:
                st.warning("Non-personalized model not found. Run the notebook first.")
                st.info(f"Looking for: {model_path}")
    except Exception as e:
        st.error(f"Error loading non-personalized model: {e}")
    
    # Load content-based model
    try:
        # Try best_model first
        model_path = base_path / 'models' / 'content_based_best_model.pkl'
        if model_path.exists():
            models['content_based'] = joblib.load(str(model_path))
            st.success("Content-based model loaded successfully")
        elif (base_path / 'models' / 'content_based_random_forest.pkl').exists():
            models['content_based'] = joblib.load(str(base_path / 'models' / 'content_based_random_forest.pkl'))
            st.success("Content-based model loaded successfully")
        else:
            # Try relative paths as fallback
            if os.path.exists('models/content_based_best_model.pkl'):
                models['content_based'] = joblib.load('models/content_based_best_model.pkl')
                st.success("Content-based model loaded successfully")
            elif os.path.exists('models/content_based_random_forest.pkl'):
                models['content_based'] = joblib.load('models/content_based_random_forest.pkl')
                st.success("Content-based model loaded successfully")
            else:
                st.warning("Content-based model not found. Run the notebook first.")
                st.info(f"Looking for: {base_path / 'models' / 'content_based_best_model.pkl'}")
    except Exception as e:
        st.error(f"Error loading content-based model: {e}")
    
    return models

def main():
    """Main application"""
    
    # Header with icons
    st.markdown("""
        <div class="app-header">
            <h1><i class="fas fa-film icon-inline"></i>MovieLens Recommender</h1>
            <p>Intelligent Movie Recommendations Powered by Machine Learning</p>
        </div>
    """, unsafe_allow_html=True)
    
    # Sidebar navigation
    with st.sidebar:
        st.markdown("### <i class='fas fa-compass icon-inline'></i>Navigation")
        page = st.radio(
            "Select a page:",
            ["Home", "Get Recommendations", "Find Similar Movies", 
             "Business Insights", "Model Performance"],
            label_visibility="collapsed"
        )
        
        st.markdown("---")
        
        st.markdown("### <i class='fas fa-info-circle icon-inline'></i>About")
        st.markdown("""
        This application demonstrates an end-to-end recommendation system 
        built using the MovieLens dataset.
        
        **Features:**
        - Non-personalized recommendations
        - Content-based filtering
        - Similar movie discovery
        - Business intelligence insights
        """)
        
        st.markdown("---")
        
        # Load models button
        if st.button("Load Models", use_container_width=True):
            with st.spinner("Loading models..."):
                base_path = Path(__file__).parent
                st.info(f"Working directory: {base_path}")
                
                models_dir = base_path / 'models'
                if models_dir.exists():
                    model_files = list(models_dir.glob('*.pkl'))
                    if model_files:
                        st.info(f"Found {len(model_files)} model file(s): {[f.name for f in model_files]}")
                    else:
                        st.warning(f"models/ directory exists but no .pkl files found")
                else:
                    st.warning(f"models/ directory not found at {models_dir}")
                
                models = load_models()
                if models:
                    st.session_state.non_pers_model = models.get('non_personalized')
                    st.session_state.content_model = models.get('content_based')
                    st.session_state.models_loaded = True
                    if st.session_state.non_pers_model and st.session_state.content_model:
                        st.success("All models loaded successfully!")
                    elif st.session_state.non_pers_model or st.session_state.content_model:
                        st.warning("Some models loaded, but not all")
        
        # Load data button
        if st.button("Load Data", use_container_width=True):
            with st.spinner("Loading data..."):
                movies_df, hidden_gems = load_data()
                st.session_state.movies_df = movies_df
                st.session_state.hidden_gems = hidden_gems
                st.session_state.data_loaded = True
                st.success("Data loaded successfully!")
        
        st.markdown("---")
        st.markdown("**Built with** Streamlit • Python • ML")
    
    # Route to pages
    if page == "Home":
        show_home_page()
    elif page == "Get Recommendations":
        show_recommendations_page()
    elif page == "Find Similar Movies":
        show_similar_movies_page()
    elif page == "Business Insights":
        show_insights_page()
    elif page == "Model Performance":
        show_model_performance_page()

def show_home_page():
    """Home page with overview and setup instructions"""
    
    st.markdown("## <i class='fas fa-home icon-inline'></i>Welcome to the MovieLens Recommendation System")
    
    st.markdown("""
    <div class="info-box">
        <strong><i class="fas fa-link icon-inline"></i>Connection to Notebook:</strong> This app uses models and data generated by running 
        the <code>Team_9_Final_Project.ipynb</code> notebook. Make sure you've run the notebook 
        and saved the models before using this app.
    </div>
    """, unsafe_allow_html=True)
    
    # Check if models/data are loaded
    col1, col2 = st.columns(2)
    
    with col1:
        if st.session_state.models_loaded:
            st.success("Models Loaded")
        else:
            st.warning("Models Not Loaded - Click 'Load Models' in sidebar")
    
    with col2:
        if st.session_state.data_loaded:
            st.success("Data Loaded")
        else:
            st.warning("Data Not Loaded - Click 'Load Data' in sidebar")
    
    # Quick stats
    st.markdown("---")
    st.markdown("## <i class='fas fa-chart-line icon-inline'></i>Platform Overview")
    
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.metric("Ratings", "2M+", "Analyzed")
    
    with col2:
        st.metric("Movies", "86K+", "In Catalog")
    
    with col3:
        st.metric("Users", "Thousands", "Active")
    
    with col4:
        st.metric("ML Models", "3", "Trained")
    
    st.markdown("---")
    
    # Features overview
    st.markdown("## <i class='fas fa-rocket icon-inline'></i>Key Features")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("""
        ### <i class='fas fa-bullseye icon-inline'></i>Personalized Recommendations
        Get top movie recommendations based on popularity, ratings, and content similarity.
        
        ### <i class='fas fa-search icon-inline'></i>Similar Movie Discovery
        Find movies similar to your favorites using advanced content-based filtering.
        """)
    
    with col2:
        st.markdown("""
        ### <i class='fas fa-chart-bar icon-inline'></i>Business Intelligence
        Explore comprehensive analytics on user behavior, genre performance, and trends.
        
        ### <i class='fas fa-chart-area icon-inline'></i>Model Comparison
        Compare different machine learning models and their performance metrics.
        """)
    
    st.markdown("---")
    
    # Getting started
    st.markdown("## <i class='fas fa-clipboard-list icon-inline'></i>Getting Started")
    
    with st.expander("1. Run the Notebook First", expanded=True):
        st.markdown("""
        **Important:** This app requires models and data from the notebook.
        
        1. Open `Team_9_Final_Project.ipynb`
        2. Run all cells to completion
        3. This will create:
           - `models/non_personalized_model.pkl`
           - `models/content_based_best_model.pkl`
           - `outputs/hidden_gems.csv`
           - `outputs/executive_summary.json`
        """)
    
    with st.expander("2. Load Models & Data"):
        st.markdown("""
        Once the notebook has run:
        
        1. Click **"Load Models"** in the sidebar
        2. Click **"Load Data"** in the sidebar
        3. Navigate to different pages to explore features
        """)
    
    with st.expander("3. Explore Features"):
        st.markdown("""
        - **Get Recommendations**: Top-N movies with genre filtering
        - **Find Similar Movies**: Content-based movie discovery
        - **Business Insights**: Analytics and visualizations
        - **Model Performance**: Compare ML models
        """)

def show_recommendations_page():
    """Recommendations page"""
    
    st.markdown("## <i class='fas fa-bullseye icon-inline'></i>Get Movie Recommendations")
    
    if not st.session_state.models_loaded or st.session_state.non_pers_model is None:
        st.warning("Please load models first using the sidebar button.")
        return
    
    st.markdown("""
    <div class="info-box">
        Get top movie recommendations based on our non-personalized IMDB weighted score algorithm.
    </div>
    """, unsafe_allow_html=True)
    
    # Filters
    col1, col2 = st.columns([2, 1])
    
    with col1:
        num_recommendations = st.slider("Number of recommendations", 5, 50, 10)
    
    with col2:
        genre_filter = st.selectbox(
            "Filter by genre (optional)",
            ["All Genres", "Action", "Comedy", "Drama", "Thriller", "Romance", 
             "Sci-Fi", "Horror", "Animation", "Documentary"]
        )
    
    if st.button("Get Recommendations", type="primary"):
        with st.spinner("Generating recommendations..."):
            try:
                # Get recommendations
                genre = None if genre_filter == "All Genres" else genre_filter
                recommendations = st.session_state.non_pers_model.recommend(n=num_recommendations, genre=genre)
                
                st.success(f"Found {len(recommendations)} recommendations!")
                
                # Display recommendations
                st.markdown("### Top Recommendations")
                
                for idx, row in recommendations.iterrows():
                    st.markdown(f"""
                        <div class="movie-card">
                            <div class="movie-title"><i class="fas fa-film icon-inline"></i>{idx+1}. {row['title']}</div>
                            <div class="movie-genre"><i class="fas fa-tags icon-inline"></i>{row['genres']}</div>
                            <div class="movie-rating"><i class="fas fa-star icon-inline"></i>{row['avg_rating']:.2f}/5.0 • {int(row['num_ratings']):,} ratings</div>
                            <div style="color: #8b5cf6; font-size: 0.9rem; margin-top: 0.5rem;"><i class="fas fa-chart-line icon-inline"></i>Score: {row['weighted_score']:.3f}</div>
                        </div>
                    """, unsafe_allow_html=True)
            except Exception as e:
                st.error(f"Error generating recommendations: {e}")
                st.info("Make sure the model was trained correctly in the notebook.")

def show_similar_movies_page():
    """Similar movies finder page"""
    
    st.markdown("## <i class='fas fa-search icon-inline'></i>Find Similar Movies")
    
    if not st.session_state.models_loaded or st.session_state.content_model is None:
        st.warning("Please load models first using the sidebar button.")
        return
    
    if st.session_state.movies_df is None or st.session_state.movies_df.empty:
        st.warning("Please load data first using the sidebar button.")
        return
    
    st.markdown("""
    <div class="info-box">
        Search for a movie and discover similar titles based on content features.
    </div>
    """, unsafe_allow_html=True)
    
    # Search box
    movie_search = st.text_input("Search for a movie:", placeholder="e.g., Toy Story, Matrix, Inception")
    
    col1, col2 = st.columns([1, 1])
    
    with col1:
        num_similar = st.slider("Number of similar movies", 5, 20, 10)
    
    with col2:
        st.info("Using Random Forest model for similarity")
    
    if st.button("Find Similar Movies", type="primary") and movie_search:
        with st.spinner("Searching for similar movies..."):
            try:
                # Search for movie
                search_results = st.session_state.movies_df[
                    st.session_state.movies_df['title'].str.contains(movie_search, case=False, na=False)
                ]
                
                if len(search_results) == 0:
                    st.error(f"No movies found matching '{movie_search}'")
                    return
                
                # Show search results
                if len(search_results) > 1:
                    selected_title = st.selectbox(
                        "Multiple matches found. Select one:",
                        search_results['title'].tolist()
                    )
                    selected_movie = search_results[search_results['title'] == selected_title].iloc[0]
                else:
                    selected_movie = search_results.iloc[0]
                
                movie_id = selected_movie['movieId']
                movie_title = selected_movie['title']
                
                st.success(f"Finding movies similar to: **{movie_title}**")
                
                # Find similar movies
                similar_movies = st.session_state.content_model.find_similar_movies(movie_id, n=num_similar)
                
                st.markdown(f"### Movies Similar to: {movie_title}")
                
                for idx, row in similar_movies.iterrows():
                    st.markdown(f"""
                        <div class="movie-card">
                            <div class="movie-title"><i class="fas fa-film icon-inline"></i>{idx+1}. {row['title']}</div>
                            <div class="movie-genre"><i class="fas fa-tags icon-inline"></i>{row['genres']}</div>
                            <div style="color: #8b5cf6; font-size: 0.9rem; margin-top: 0.5rem;"><i class="fas fa-calendar icon-inline"></i>Year: {row.get('release_year', 'N/A')}</div>
                        </div>
                    """, unsafe_allow_html=True)
            except Exception as e:
                st.error(f"Error finding similar movies: {e}")
                st.info("Make sure the content-based model was trained correctly in the notebook.")

def show_insights_page():
    """Business insights page"""
    
    st.markdown("## <i class='fas fa-chart-bar icon-inline'></i>Business Intelligence Dashboard")
    
    if not st.session_state.data_loaded:
        st.warning("Please load data first using the sidebar button.")
        st.info("The notebook generates comprehensive insights. This page shows key metrics.")
        return
    
    # Tabs for different insights
    tab1, tab2, tab3, tab4 = st.tabs(["Overview", "User Behavior", "Content Performance", "Hidden Gems"])
    
    with tab1:
        st.markdown("### Executive Summary")
        
        # Try to load executive summary
        try:
            if os.path.exists('outputs/executive_summary.json'):
                import json
                with open('outputs/executive_summary.json', 'r') as f:
                    summary = json.load(f)
                
                col1, col2, col3, col4 = st.columns(4)
                
                with col1:
                    st.metric("Total Ratings", summary.get('total_ratings', 'N/A'))
                with col2:
                    st.metric("Active Users", summary.get('unique_users', 'N/A'))
                with col3:
                    st.metric("Platform Rating", summary.get('avg_rating', 'N/A'))
                with col4:
                    st.metric("Best Model", summary.get('best_model', 'N/A'))
                
                st.markdown("---")
                st.markdown("""
                <div class="info-box">
                    <strong>Key Insights:</strong>
                    <ul>
                        <li>User engagement metrics from comprehensive analysis</li>
                        <li>Genre performance data available in notebook</li>
                        <li>Temporal trends analyzed in detail</li>
                        <li>Power users identified for targeted strategies</li>
                    </ul>
                </div>
                """, unsafe_allow_html=True)
            else:
                st.info("Run the notebook to generate executive summary. Check outputs/executive_summary.json")
        except Exception as e:
            st.warning(f"Could not load executive summary: {e}")
    
    with tab2:
        st.markdown("### User Segmentation")
        st.markdown("Analysis of user behavior patterns and engagement levels.")
        st.info("Detailed user segmentation analysis is available in the notebook (Part 4).")
        st.markdown("""
        **Key Segments Identified:**
        - Power Users (100+ ratings)
        - Active Users (20-100 ratings)
        - Casual Users (<20 ratings)
        - Generous vs Critical Raters
        """)
    
    with tab3:
        st.markdown("### Genre Performance")
        st.markdown("Comprehensive analysis of genre ratings and popularity.")
        st.info("Detailed genre performance analysis with engagement scores is available in the notebook (Part 4).")
        st.markdown("""
        **Analysis Includes:**
        - Average rating by genre
        - Total ratings per genre
        - Engagement scores
        - Risk vs reward assessment
        """)
    
    with tab4:
        st.markdown("### Hidden Gems Discovery")
        st.markdown("High-rated movies with low visibility - perfect for recommendations.")
        
        if st.session_state.hidden_gems is not None and not st.session_state.hidden_gems.empty:
            st.dataframe(
                st.session_state.hidden_gems.head(20)[['title', 'genres', 'avg_rating', 'num_ratings', 'gem_score']],
                use_container_width=True
            )
        else:
            st.info("Run the notebook to generate hidden gems data. Check outputs/hidden_gems.csv")

def show_model_performance_page():
    """Model performance comparison page"""
    
    st.markdown("## <i class='fas fa-chart-area icon-inline'></i>Model Performance Comparison")
    
    st.markdown("""
    <div class="info-box">
        Comparison of different content-based recommendation models trained in the notebook.
    </div>
    """, unsafe_allow_html=True)
    
    # Try to load model comparison
    try:
        if os.path.exists('outputs/model_comparison.csv'):
            comparison_df = pd.read_csv('outputs/model_comparison.csv')
            
            st.markdown("### Performance Metrics")
            
            col1, col2, col3 = st.columns(3)
            
            with col1:
                best_model = comparison_df.loc[comparison_df['RMSE'].idxmin()]
                st.markdown("#### <i class='fas fa-trophy icon-inline'></i>Best Model: " + best_model['Model'])
                st.metric("RMSE", f"{best_model['RMSE']:.4f}", "Lower is better")
                st.metric("MAE", f"{best_model['MAE']:.4f}", "Lower is better")
                st.metric("Accuracy", f"{best_model['Accuracy']:.2%}", "Higher is better")
                st.success("Recommended for Production")
            
            with col2:
                if len(comparison_df) > 1:
                    second = comparison_df.nsmallest(2, 'RMSE').iloc[1]
                    st.markdown("#### " + second['Model'])
                    st.metric("RMSE", f"{second['RMSE']:.4f}")
                    st.metric("MAE", f"{second['MAE']:.4f}")
                    st.metric("Accuracy", f"{second['Accuracy']:.2%}")
                    st.info("Fast Training")
            
            with col3:
                if len(comparison_df) > 2:
                    third = comparison_df.nlargest(1, 'RMSE').iloc[0]
                    st.markdown("#### " + third['Model'])
                    st.metric("RMSE", f"{third['RMSE']:.4f}")
                    st.metric("MAE", f"{third['MAE']:.4f}")
                    st.metric("Accuracy", f"{third['Accuracy']:.2%}")
                    st.warning("Baseline Model")
            
            st.markdown("---")
            st.markdown("### Detailed Comparison")
            st.dataframe(comparison_df, use_container_width=True)
            
            st.markdown("---")
            st.markdown("### Model Recommendations")
            st.markdown("""
            **Based on comprehensive evaluation:**
            
            1. **Random Forest** - Best for production deployment
               - Highest accuracy and lowest error rates
               - Good balance between performance and training time
               - Robust to overfitting with proper tuning
            
            2. **Ridge Regression** - Best for rapid iteration
               - Fastest training time
               - Acceptable performance for most use cases
               - Easy to interpret and maintain
            
            3. **KNN** - Baseline comparison
               - Simple implementation
               - Useful for similarity-based recommendations
               - Can be slow with large datasets
            """)
        else:
            st.info("Run the notebook to generate model comparison. Check outputs/model_comparison.csv")
            st.markdown("""
            **Expected Models:**
            - Random Forest (Best Performance)
            - Ridge Regression (Fast Training)
            - K-Nearest Neighbors (Baseline)
            """)
    except Exception as e:
        st.error(f"Error loading model comparison: {e}")

if __name__ == "__main__":
    main()
