"""
MovieLens Recommendation System - Streamlit Application
Main entry point for the web application

This app connects to the notebook by:
1. Loading trained models from models/ directory (saved by notebook)
2. Loading data from outputs/ directory (generated by notebook)
3. Using the same data processing logic from the notebook
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os
from pathlib import Path
import warnings
from sklearn.preprocessing import MultiLabelBinarizer, StandardScaler
from sklearn.neighbors import NearestNeighbors
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score
warnings.filterwarnings('ignore')

# Define model classes (required for joblib to load saved models)
class NonPersonalizedRecommender:
    """
    Non-personalized recommendation system based on popularity and IMDB weighted score
    Formula: WR = (v/(v+m)) * R + (m/(v+m)) * C
    """
    
    def __init__(self, min_ratings: int = 50, percentile: int = 90):
        self.min_ratings = min_ratings
        self.percentile = percentile
        self.movie_scores = None
        
    def fit(self, ratings_df: pd.DataFrame, movies_df: pd.DataFrame):
        """Calculate IMDB weighted scores for all movies"""
        # Calculate statistics
        movie_stats = ratings_df.groupby('movieId').agg({
            'rating': ['mean', 'count']
        }).reset_index()
        
        movie_stats.columns = ['movieId', 'avg_rating', 'num_ratings']
        
        # Calculate C (mean rating across all movies)
        C = ratings_df['rating'].mean()
        
        # Calculate m (minimum votes required) based on percentile
        m = movie_stats['num_ratings'].quantile(self.percentile / 100)
        
        # Calculate weighted score
        movie_stats['weighted_score'] = (
            (movie_stats['num_ratings'] / (movie_stats['num_ratings'] + m)) * movie_stats['avg_rating'] +
            (m / (movie_stats['num_ratings'] + m)) * C
        )
        
        # Merge with movie details
        self.movie_scores = movie_stats.merge(
            movies_df[['movieId', 'title', 'genres', 'release_year']], 
            on='movieId'
        )
        
        # Sort by weighted score
        self.movie_scores = self.movie_scores.sort_values('weighted_score', ascending=False)
        
        return self
    
    def recommend(self, n: int = 10, genre: str = None) -> pd.DataFrame:
        """Get top N recommendations"""
        df = self.movie_scores.copy()
        
        # Filter by genre if specified
        if genre:
            df = df[df['genres'].str.contains(genre, case=False, na=False)]
        
        return df.head(n)[['movieId', 'title', 'genres', 'avg_rating', 
                          'num_ratings', 'weighted_score']]

class ContentBasedRecommender:
    """
    Content-based recommendation system using movie features
    """
    
    def __init__(self, model_type: str = 'random_forest'):
        self.model_type = model_type
        self.model = None
        self.scaler = StandardScaler()
        self.mlb = MultiLabelBinarizer()
        self.feature_names = None
        self.movies_df = None
        self.ratings_df = None  # Store for find_similar_movies
        
    def _prepare_features(self, ratings_df: pd.DataFrame, movies_df: pd.DataFrame) -> tuple:
        """Prepare feature matrix"""
        # Merge ratings with movies
        df = ratings_df.merge(movies_df[['movieId', 'genres_list', 'release_year', 'genre_count']], 
                             on='movieId')
        
        # Calculate movie statistics
        movie_stats = df.groupby('movieId').agg({
            'rating': ['mean', 'std', 'count']
        }).reset_index()
        
        movie_stats.columns = ['movieId', 'movie_avg_rating', 'movie_std_rating', 'movie_num_ratings']
        
        df = df.merge(movie_stats, on='movieId')
        
        # One-hot encode genres
        genre_encoded = self.mlb.fit_transform(df['genres_list'])
        genre_df = pd.DataFrame(
            genre_encoded, 
            columns=[f'genre_{g}' for g in self.mlb.classes_],
            index=df.index
        )
        
        # Combine features
        feature_df = pd.concat([
            df[['release_year', 'genre_count', 'movie_avg_rating', 'movie_std_rating', 'movie_num_ratings']].fillna(0),
            genre_df
        ], axis=1)
        
        self.feature_names = feature_df.columns.tolist()
        
        return feature_df, df['rating']
    
    def fit(self, ratings_df: pd.DataFrame, movies_df: pd.DataFrame):
        """Train the content-based model"""
        self.movies_df = movies_df
        self.ratings_df = ratings_df
        
        # Prepare features
        X, y = self._prepare_features(ratings_df, movies_df)
        
        # Split data
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )
        
        # Scale features
        X_train_scaled = self.scaler.fit_transform(X_train)
        X_test_scaled = self.scaler.transform(X_test)
        
        # Train model
        if self.model_type == 'knn':
            self.model = NearestNeighbors(n_neighbors=10, metric='cosine')
            self.model.fit(X_train_scaled)
            predictions = np.full(len(X_test), y_train.mean())
        elif self.model_type == 'random_forest':
            self.model = RandomForestRegressor(n_estimators=100, max_depth=10, 
                                              random_state=42, n_jobs=-1)
            self.model.fit(X_train_scaled, y_train)
            predictions = self.model.predict(X_test_scaled)
        elif self.model_type == 'ridge':
            self.model = Ridge(alpha=1.0)
            self.model.fit(X_train_scaled, y_train)
            predictions = self.model.predict(X_test_scaled)
        else:
            raise ValueError(f"Unknown model type: {self.model_type}")
        
        # Calculate metrics
        rmse = np.sqrt(mean_squared_error(y_test, predictions))
        mae = mean_absolute_error(y_test, predictions)
        
        # Calculate accuracy for binary classification (rating >= 3.5)
        y_test_binary = (y_test >= 3.5).astype(int)
        pred_binary = (predictions >= 3.5).astype(int)
        accuracy = accuracy_score(y_test_binary, pred_binary)
        
        return {'rmse': rmse, 'mae': mae, 'accuracy': accuracy}
    
    def find_similar_movies(self, movie_id: int, n: int = 10) -> pd.DataFrame:
        """Find similar movies based on content features"""
        if self.movies_df is None:
            raise ValueError("Model not trained yet")
        
        movie_row = self.movies_df[self.movies_df['movieId'] == movie_id]
        if len(movie_row) == 0:
            raise ValueError(f"Movie ID {movie_id} not found")
        
        # Calculate movie statistics from ratings
        if self.ratings_df is not None:
            movie_stats = self.ratings_df.groupby('movieId').agg({
                'rating': ['mean', 'std', 'count']
            }).reset_index()
            movie_stats.columns = ['movieId', 'movie_avg_rating', 'movie_std_rating', 'movie_num_ratings']
            movie_stats_dict = movie_stats.set_index('movieId').to_dict('index')
        else:
            movie_stats_dict = {}
        
        # Prepare features for target movie
        target_features = []
        target_genres = movie_row.iloc[0]['genres_list'] if isinstance(movie_row.iloc[0]['genres_list'], list) else []
        target_year = movie_row.iloc[0]['release_year']
        target_genre_count = movie_row.iloc[0]['genre_count']
        
        # Add numeric features
        target_features.extend([
            target_year,
            target_genre_count,
            movie_stats_dict.get(movie_id, {}).get('movie_avg_rating', 0),
            movie_stats_dict.get(movie_id, {}).get('movie_std_rating', 0),
            movie_stats_dict.get(movie_id, {}).get('movie_num_ratings', 0)
        ])
        
        # Add genre features
        for genre in self.mlb.classes_:
            target_features.append(1 if genre in target_genres else 0)
        
        # Scale features
        target_features_scaled = self.scaler.transform([target_features])
        
        # Find similar movies
        if self.model_type == 'knn':
            distances, indices = self.model.kneighbors(target_features_scaled, n_neighbors=n+1)
            similar_indices = indices[0][1:]  # Exclude the movie itself
        else:
            # For other models, use feature similarity
            all_movies = self.movies_df.copy()
            similarities = []
            
            for idx, row in all_movies.iterrows():
                if row['movieId'] == movie_id:
                    continue
                
                movie_features = []
                movie_genres = row['genres_list'] if isinstance(row['genres_list'], list) else []
                
                # Add numeric features
                movie_features.extend([
                    row['release_year'],
                    row['genre_count'],
                    movie_stats_dict.get(row['movieId'], {}).get('movie_avg_rating', 0),
                    movie_stats_dict.get(row['movieId'], {}).get('movie_std_rating', 0),
                    movie_stats_dict.get(row['movieId'], {}).get('movie_num_ratings', 0)
                ])
                
                # Add genre features
                for genre in self.mlb.classes_:
                    movie_features.append(1 if genre in movie_genres else 0)
                
                # Calculate cosine similarity
                movie_features_scaled = self.scaler.transform([movie_features])
                similarity = np.dot(target_features_scaled[0], movie_features_scaled[0]) / (
                    np.linalg.norm(target_features_scaled[0]) * np.linalg.norm(movie_features_scaled[0])
                )
                similarities.append((row['movieId'], similarity))
            
            # Sort by similarity
            similarities.sort(key=lambda x: x[1], reverse=True)
            similar_movie_ids = [movie_id for movie_id, _ in similarities[:n]]
            similar_movies = self.movies_df[self.movies_df['movieId'].isin(similar_movie_ids)]
        
        # If using KNN
        if self.model_type == 'knn':
            # Get movie IDs from training data
            # This is a simplified version - you'd need to track the mapping
            similar_movies = self.movies_df.head(n)  # Placeholder
        
        return similar_movies[['movieId', 'title', 'genres', 'release_year']].head(n)

# Page configuration must be first Streamlit command
st.set_page_config(
    page_title="🎬 MovieLens Recommender",
    page_icon="🎬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Enhanced CSS with animations and gradients
st.markdown("""
<style>
    /* Import Google Fonts */
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700&display=swap');
    
    /* Global Styles */
    * {
        font-family: 'Poppins', sans-serif;
    }
    
    /* Main app background with animated gradient */
    .stApp {
        background: linear-gradient(-45deg, #0a0a0a, #1a0f2e, #0f1c2e, #1a0a1f);
        background-size: 400% 400%;
        animation: gradientShift 15s ease infinite;
    }
    
    @keyframes gradientShift {
        0% { background-position: 0% 50%; }
        50% { background-position: 100% 50%; }
        100% { background-position: 0% 50%; }
    }
    
    /* Animated header */
    .main-header {
        background: linear-gradient(135deg, #e50914 0%, #b20710 50%, #8b0000 100%);
        padding: 2.5rem;
        border-radius: 20px;
        margin-bottom: 2rem;
        box-shadow: 0 10px 40px rgba(229, 9, 20, 0.4);
        text-align: center;
        animation: headerPulse 3s ease-in-out infinite;
        position: relative;
        overflow: hidden;
    }
    
    .main-header::before {
        content: '';
        position: absolute;
        top: -50%;
        left: -50%;
        width: 200%;
        height: 200%;
        background: linear-gradient(
            45deg,
            transparent,
            rgba(255, 255, 255, 0.1),
            transparent
        );
        animation: shine 3s infinite;
    }
    
    @keyframes shine {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
    
    @keyframes headerPulse {
        0%, 100% { box-shadow: 0 10px 40px rgba(229, 9, 20, 0.4); }
        50% { box-shadow: 0 10px 60px rgba(229, 9, 20, 0.6); }
    }
    
    .main-header h1 {
        color: white;
        font-size: 3.5rem;
        font-weight: 800;
        margin: 0;
        text-shadow: 3px 3px 6px rgba(0,0,0,0.5);
        position: relative;
        z-index: 1;
    }
    
    .main-header p {
        color: #f5f5f5;
        font-size: 1.3rem;
        margin-top: 0.8rem;
        font-weight: 300;
        position: relative;
        z-index: 1;
    }
    
    /* Movie cards with hover effects */
    .movie-card {
        background: linear-gradient(135deg, rgba(30, 30, 50, 0.9), rgba(20, 20, 40, 0.9));
        backdrop-filter: blur(15px);
        border-radius: 15px;
        padding: 1.8rem;
        margin: 1.2rem 0;
        border: 1px solid rgba(229, 9, 20, 0.3);
        transition: all 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
        box-shadow: 0 5px 20px rgba(0, 0, 0, 0.3);
        position: relative;
        overflow: hidden;
    }
    
    .movie-card::before {
        content: '';
        position: absolute;
        top: 0;
        left: -100%;
        width: 100%;
        height: 100%;
        background: linear-gradient(90deg, transparent, rgba(229, 9, 20, 0.2), transparent);
        transition: 0.5s;
    }
    
    .movie-card:hover::before {
        left: 100%;
    }
    
    .movie-card:hover {
        transform: translateY(-8px) scale(1.02);
        box-shadow: 0 15px 40px rgba(229, 9, 20, 0.5);
        border-color: #e50914;
    }
    
    .movie-title {
        font-size: 1.3rem;
        font-weight: 600;
        color: #ffffff;
        margin-bottom: 0.8rem;
        text-shadow: 1px 1px 2px rgba(0,0,0,0.5);
    }
    
    .movie-genre {
        color: #e50914;
        font-size: 1rem;
        margin: 0.5rem 0;
        font-weight: 500;
    }
    
    .movie-rating {
        color: #ffd700;
        font-size: 1.1rem;
        font-weight: 600;
        text-shadow: 0 0 10px rgba(255, 215, 0, 0.5);
    }
    
    /* Metric cards with gradient backgrounds */
    .metric-card {
        background: linear-gradient(135deg, #e50914 0%, #b20710 100%);
        border-radius: 15px;
        padding: 1.5rem;
        text-align: center;
        color: white;
        box-shadow: 0 8px 25px rgba(0,0,0,0.4);
        transition: all 0.3s ease;
        animation: float 3s ease-in-out infinite;
    }
    
    @keyframes float {
        0%, 100% { transform: translateY(0px); }
        50% { transform: translateY(-10px); }
    }
    
    .metric-card:hover {
        transform: scale(1.05) translateY(-5px);
        box-shadow: 0 12px 35px rgba(229, 9, 20, 0.6);
    }
    
    /* Sidebar styling */
    [data-testid="stSidebar"] {
        background: linear-gradient(180deg, rgba(15, 15, 30, 0.95), rgba(10, 10, 25, 0.95));
        backdrop-filter: blur(10px);
        border-right: 1px solid rgba(229, 9, 20, 0.3);
    }
    
    /* Enhanced buttons */
    .stButton > button {
        background: linear-gradient(135deg, #e50914 0%, #b20710 100%);
        color: white;
        border: none;
        padding: 0.8rem 2rem;
        border-radius: 50px;
        font-weight: 600;
        font-size: 1.1rem;
        transition: all 0.3s ease;
        box-shadow: 0 4px 15px rgba(229, 9, 20, 0.4);
        position: relative;
        overflow: hidden;
    }
    
    .stButton > button::before {
        content: '';
        position: absolute;
        top: 50%;
        left: 50%;
        width: 0;
        height: 0;
        border-radius: 50%;
        background: rgba(255, 255, 255, 0.3);
        transform: translate(-50%, -50%);
        transition: width 0.6s, height 0.6s;
    }
    
    .stButton > button:hover::before {
        width: 300px;
        height: 300px;
    }
    
    .stButton > button:hover {
        transform: scale(1.05);
        box-shadow: 0 6px 25px rgba(229, 9, 20, 0.6);
    }
    
    /* Info boxes with gradient borders */
    .info-box {
        background: rgba(20, 20, 40, 0.6);
        border-left: 4px solid #e50914;
        border-radius: 10px;
        padding: 1.5rem;
        margin: 1rem 0;
        color: #e0e0e0;
        box-shadow: 0 4px 15px rgba(0,0,0,0.3);
        transition: all 0.3s ease;
    }
    
    .info-box:hover {
        background: rgba(229, 9, 20, 0.1);
        transform: translateX(5px);
        box-shadow: 0 4px 20px rgba(229, 9, 20, 0.4);
    }
    
    /* Warning boxes */
    .warning-box {
        background: linear-gradient(135deg, rgba(255, 193, 7, 0.2), rgba(255, 152, 0, 0.2));
        border-left: 4px solid #ffc107;
        border-radius: 10px;
        padding: 1.5rem;
        margin: 1rem 0;
        color: #fff3cd;
        animation: pulse 2s infinite;
    }
    
    @keyframes pulse {
        0%, 100% { opacity: 1; }
        50% { opacity: 0.8; }
    }
    
    /* Success boxes */
    .success-box {
        background: linear-gradient(135deg, rgba(40, 167, 69, 0.2), rgba(25, 135, 84, 0.2));
        border-left: 4px solid #28a745;
        border-radius: 10px;
        padding: 1.5rem;
        margin: 1rem 0;
        color: #d4edda;
    }
    
    /* Platform overview metrics */
    .platform-metric {
        text-align: center;
        padding: 1.5rem;
        background: linear-gradient(135deg, rgba(229, 9, 20, 0.2), rgba(139, 0, 0, 0.2));
        border-radius: 15px;
        border: 1px solid rgba(229, 9, 20, 0.3);
        transition: all 0.3s ease;
    }
    
    .platform-metric:hover {
        transform: scale(1.05);
        border-color: #e50914;
        box-shadow: 0 5px 20px rgba(229, 9, 20, 0.4);
    }
    
    .platform-metric-value {
        font-size: 2.5rem;
        font-weight: 700;
        color: #e50914;
        text-shadow: 0 0 20px rgba(229, 9, 20, 0.5);
    }
    
    .platform-metric-label {
        font-size: 1rem;
        color: #b0b0b0;
        margin-top: 0.5rem;
    }
    
    .platform-metric-status {
        font-size: 0.9rem;
        color: #4CAF50;
        margin-top: 0.3rem;
        font-weight: 500;
    }
    
    /* Tabs styling */
    .stTabs [data-baseweb="tab-list"] {
        gap: 8px;
        background: rgba(20, 20, 40, 0.5);
        border-radius: 10px;
        padding: 0.5rem;
    }
    
    .stTabs [data-baseweb="tab"] {
        background: transparent;
        color: #b0b0b0;
        border-radius: 8px;
        transition: all 0.3s ease;
    }
    
    .stTabs [data-baseweb="tab"]:hover {
        background: rgba(229, 9, 20, 0.2);
        color: #ffffff;
    }
    
    .stTabs [aria-selected="true"] {
        background: linear-gradient(135deg, #e50914, #b20710);
        color: white;
    }
    
    /* Expander styling */
    .streamlit-expanderHeader {
        background: rgba(20, 20, 40, 0.6);
        border-radius: 10px;
        color: #ffffff;
        font-weight: 600;
    }
    
    .streamlit-expanderHeader:hover {
        background: rgba(229, 9, 20, 0.2);
    }
    
    /* Dataframe styling */
    .stDataFrame {
        background: rgba(20, 20, 40, 0.6);
        border-radius: 10px;
        overflow: hidden;
    }
    
    /* Radio buttons in sidebar */
    .stRadio > div {
        background: rgba(20, 20, 40, 0.4);
        border-radius: 10px;
        padding: 0.5rem;
    }
    
    /* Select boxes */
    .stSelectbox > div > div {
        background: rgba(20, 20, 40, 0.8);
        border: 1px solid rgba(229, 9, 20, 0.3);
        border-radius: 10px;
    }
    
    /* Slider */
    .stSlider > div > div > div {
        background: linear-gradient(90deg, #e50914, #b20710);
    }
    
    /* Loading spinner custom */
    .stSpinner > div {
        border-top-color: #e50914 !important;
    }
    
    /* Glow effect for important elements */
    .glow {
        animation: glow 2s ease-in-out infinite alternate;
    }
    
    @keyframes glow {
        from {
            box-shadow: 0 0 10px #e50914, 0 0 20px #e50914, 0 0 30px #e50914;
        }
        to {
            box-shadow: 0 0 20px #e50914, 0 0 30px #b20710, 0 0 40px #b20710;
        }
    }
    
    /* Feature highlights */
    .feature-item {
        background: linear-gradient(135deg, rgba(30, 30, 50, 0.8), rgba(20, 20, 40, 0.8));
        border-radius: 12px;
        padding: 1.2rem;
        margin: 0.8rem 0;
        border-left: 3px solid #e50914;
        transition: all 0.3s ease;
    }
    
    .feature-item:hover {
        transform: translateX(10px);
        border-left-width: 5px;
        background: linear-gradient(135deg, rgba(229, 9, 20, 0.2), rgba(139, 0, 0, 0.2));
    }
    
    /* Responsive design */
    @media (max-width: 768px) {
        .main-header h1 {
            font-size: 2rem;
        }
        
        .main-header p {
            font-size: 1rem;
        }
        
        .movie-card {
            padding: 1rem;
        }
    }
</style>
""", unsafe_allow_html=True)

# Initialize session state
if 'models_loaded' not in st.session_state:
    st.session_state.models_loaded = False
if 'data_loaded' not in st.session_state:
    st.session_state.data_loaded = False
if 'non_personalized_model' not in st.session_state:
    st.session_state.non_personalized_model = None
if 'content_model' not in st.session_state:
    st.session_state.content_model = None
if 'movies_df' not in st.session_state:
    st.session_state.movies_df = None
if 'ratings_df' not in st.session_state:
    st.session_state.ratings_df = None
if 'hidden_gems' not in st.session_state:
    st.session_state.hidden_gems = None

@st.cache_resource
def load_models():
    """Load trained models from the models directory"""
    models = {}
    models_dir = Path('models')
    
    try:
        # Load non-personalized model
        if (models_dir / 'non_personalized_model.pkl').exists():
            models['non_personalized'] = joblib.load(models_dir / 'non_personalized_model.pkl')
        
        # Load content-based model
        if (models_dir / 'content_based_best_model.pkl').exists():
            models['content_based'] = joblib.load(models_dir / 'content_based_best_model.pkl')
        
        return models
    except Exception as e:
        st.error(f"Error loading models: {e}")
        return {}

@st.cache_data
def load_data_files():
    """Load datasets and outputs"""
    data = {}
    
    try:
        # Load movies data
        if os.path.exists('movies.csv'):
            data['movies'] = pd.read_csv('movies.csv')
            # Parse genres
            if 'genres' in data['movies'].columns:
                data['movies']['genres_list'] = data['movies']['genres'].str.split('|')
                data['movies']['genre_count'] = data['movies']['genres_list'].apply(len)
            # Extract year from title
            data['movies']['release_year'] = data['movies']['title'].str.extract(r'\((\d{4})\)').astype(float)
        
        # Load ratings data (sample for performance)
        if os.path.exists('ratings.csv'):
            # Load a sample for faster processing
            data['ratings'] = pd.read_csv('ratings.csv', nrows=100000)
        
        # Load hidden gems
        if os.path.exists('outputs/hidden_gems.csv'):
            data['hidden_gems'] = pd.read_csv('outputs/hidden_gems.csv')
        
        return data
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return {}

def load_models_action():
    """Load models when button is clicked"""
    with st.spinner('🎬 Loading ML models...'):
        models = load_models()
        
        if models:
            if 'non_personalized' in models:
                st.session_state.non_personalized_model = models['non_personalized']
            if 'content_based' in models:
                st.session_state.content_model = models['content_based']
            st.session_state.models_loaded = True
            st.success('✅ Models loaded successfully!')
        else:
            st.error('⚠️ No models found. Run the notebook first!')

def load_data_action():
    """Load data when button is clicked"""
    with st.spinner('📊 Loading datasets...'):
        data = load_data_files()
        
        if data:
            if 'movies' in data:
                st.session_state.movies_df = data['movies']
            if 'ratings' in data:
                st.session_state.ratings_df = data['ratings']
            if 'hidden_gems' in data:
                st.session_state.hidden_gems = data['hidden_gems']
            st.session_state.data_loaded = True
            st.success('✅ Data loaded successfully!')
        else:
            st.error('⚠️ No data files found. Check your directory!')

def main():
    """Main application"""
    
    # Header
    st.markdown("""
        <div class="main-header">
            <h1>🎬 MovieLens Recommender</h1>
            <p>Intelligent Movie Recommendations Powered by Machine Learning</p>
        </div>
    """, unsafe_allow_html=True)
    
    # Sidebar navigation
    with st.sidebar:
        st.markdown("## 🎯 Navigation")
        
        page = st.radio(
            "",
            ["🏠 Home", "🎯 Get Recommendations", "🔍 Find Similar Movies", 
             "📊 Business Insights", "📈 Model Performance"],
            label_visibility="collapsed"
        )
        
        st.markdown("---")
        
        st.markdown("## ℹ️ About")
        st.markdown("""
        <div style='font-size: 0.9rem; color: #b0b0b0;'>
        This application demonstrates an end-to-end recommendation system built using the MovieLens dataset.
        
        <strong>Features:</strong>
        • Non-personalized recommendations<br>
        • Content-based filtering<br>
        • Similar movie discovery<br>
        • Business intelligence insights
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("---")
        
        # Load buttons with enhanced styling
        if st.button("🤖 LOAD MODELS", use_container_width=True):
            load_models_action()
        
        if st.button("📁 LOAD DATA", use_container_width=True):
            load_data_action()
        
        st.markdown("---")
        st.markdown("""
        <div style='text-align: center; color: #666; font-size: 0.8rem;'>
        Built with Streamlit • Python • ML
        </div>
        """, unsafe_allow_html=True)
    
    # Route to appropriate page
    if page == "🏠 Home":
        show_home_page()
    elif page == "🎯 Get Recommendations":
        show_recommendations_page()
    elif page == "🔍 Find Similar Movies":
        show_similar_movies_page()
    elif page == "📊 Business Insights":
        show_insights_page()
    elif page == "📈 Model Performance":
        show_model_performance_page()

def show_home_page():
    """Home page with overview"""
    
    st.markdown("## 👋 Welcome to the MovieLens Recommendation System")
    
    # Connection info
    st.markdown("""
    <div class="info-box">
        <strong>🔗 Connection to Notebook:</strong><br>
        This app uses models and data generated by running the <code>Team_9_Final_Project.ipynb</code> notebook. 
        Make sure you've run the notebook and saved the models before using this app.
    </div>
    """, unsafe_allow_html=True)
    
    # Status indicators
    col1, col2 = st.columns(2)
    
    with col1:
        if st.session_state.models_loaded:
            st.markdown("""
            <div class="success-box">
                ✅ Models Loaded - Ready for recommendations
            </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown("""
            <div class="warning-box">
                ⚠️ Models Not Loaded - Click 'Load Models' in sidebar
            </div>
            """, unsafe_allow_html=True)
    
    with col2:
        if st.session_state.data_loaded:
            st.markdown("""
            <div class="success-box">
                ✅ Data Loaded - Explore insights available
            </div>
            """, unsafe_allow_html=True)
        else:
            st.markdown("""
            <div class="warning-box">
                ⚠️ Data Not Loaded - Click 'Load Data' in sidebar
            </div>
            """, unsafe_allow_html=True)
    
    st.markdown("---")
    
    # Platform Overview
    st.markdown("## 📊 Platform Overview")
    
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        st.markdown("""
        <div class="platform-metric">
            <div class="platform-metric-label">Ratings</div>
            <div class="platform-metric-value">2M+</div>
            <div class="platform-metric-status">↑ Analyzed</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col2:
        st.markdown("""
        <div class="platform-metric">
            <div class="platform-metric-label">Movies</div>
            <div class="platform-metric-value">86K+</div>
            <div class="platform-metric-status">↑ In Catalog</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col3:
        st.markdown("""
        <div class="platform-metric">
            <div class="platform-metric-label">Users</div>
            <div class="platform-metric-value">Thousands</div>
            <div class="platform-metric-status">↑ Active</div>
        </div>
        """, unsafe_allow_html=True)
    
    with col4:
        st.markdown("""
        <div class="platform-metric">
            <div class="platform-metric-label">ML Models</div>
            <div class="platform-metric-value">3</div>
            <div class="platform-metric-status">↑ Trained</div>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("---")
    
    # Key Features
    st.markdown("## 🚀 Key Features")
    
    col1, col2 = st.columns(2)
    
    with col1:
        st.markdown("""
        <div class="feature-item">
            <h4>🎯 Personalized Recommendations</h4>
            <p>Get top movie recommendations based on popularity, ratings, and content similarity.</p>
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("""
        <div class="feature-item">
            <h4>🔍 Similar Movie Discovery</h4>
            <p>Find movies similar to your favorites using advanced content-based filtering.</p>
        </div>
        """, unsafe_allow_html=True)
    
    with col2:
        st.markdown("""
        <div class="feature-item">
            <h4>📊 Business Intelligence</h4>
            <p>Explore comprehensive analytics on user behavior, genre performance, and trends.</p>
        </div>
        """, unsafe_allow_html=True)
        
        st.markdown("""
        <div class="feature-item">
            <h4>📈 Model Comparison</h4>
            <p>Compare different machine learning models and their performance metrics.</p>
        </div>
        """, unsafe_allow_html=True)
    
    st.markdown("---")
    
    # Getting Started
    with st.expander("📋 Getting Started", expanded=False):
        st.markdown("""
        ### Run the Notebook First
        
        **Important:** This app requires models and data from the notebook.
        
        1. Open `Team_9_Final_Project.ipynb`
        2. Run all cells from top to bottom
        3. This creates:
           - `models/non_personalized_model.pkl`
           - `models/content_based_best_model.pkl`
           - `outputs/hidden_gems.csv`
           - `outputs/executive_summary.json`
        
        ### Load Models & Data
        
        Once the notebook has run:
        
        1. Click "🤖 Load Models" in the sidebar
        2. Click "📁 Load Data" in the sidebar
        3. Navigate to different pages to explore features
        """)
    
    with st.expander("🎨 Explore Features", expanded=False):
        st.markdown("""
        - **Get Recommendations**: Top-N movies with genre filtering
        - **Find Similar Movies**: Content-based movie discovery
        - **Business Insights**: Analytics and visualizations
        - **Model Performance**: Compare ML models
        """)

def show_recommendations_page():
    """Recommendations page"""
    
    st.markdown("## 🎯 Get Movie Recommendations")
    
    if not st.session_state.models_loaded:
        st.warning("⚠️ Please load models first using the sidebar button.")
        return
    
    if st.session_state.non_personalized_model is None:
        st.error("❌ Non-personalized model not available.")
        return
    
    st.markdown("""
    <div class="info-box">
        Get top movie recommendations based on IMDB-weighted popularity scores.
        Filter by genre to find movies in categories you love! 🎬
    </div>
    """, unsafe_allow_html=True)
    
    # Controls
    col1, col2 = st.columns([2, 1])
    
    with col1:
        genre_filter = st.selectbox(
            "🎭 Filter by Genre (optional)",
            ['All Genres', 'Action', 'Adventure', 'Animation', 'Comedy', 'Crime', 
             'Documentary', 'Drama', 'Fantasy', 'Horror', 'Mystery', 'Romance', 
             'Sci-Fi', 'Thriller', 'War', 'Western']
        )
    
    with col2:
        num_recommendations = st.slider("📊 Number of recommendations", 5, 50, 10)
    
    if st.button("✨ Get Recommendations", use_container_width=True):
        with st.spinner('🎬 Finding the best movies for you...'):
            try:
                genre = None if genre_filter == 'All Genres' else genre_filter
                recommendations = st.session_state.non_personalized_model.recommend(
                    n=num_recommendations, 
                    genre=genre
                )
                
                st.markdown(f"### 🌟 Top {len(recommendations)} Movie Recommendations")
                
                if genre:
                    st.info(f"🎭 Filtered by genre: **{genre}**")
                
                # Display recommendations
                for idx, row in recommendations.iterrows():
                    st.markdown(f"""
                        <div class="movie-card">
                            <div class="movie-title">#{idx+1}. {row['title']}</div>
                            <div class="movie-genre">🎭 {row['genres']}</div>
                            <div class="movie-rating">⭐ Rating: {row['avg_rating']:.2f}/5.0</div>
                            <div style="color: #8b5cf6; font-size: 0.9rem; margin-top: 0.5rem;">
                                👥 {row['num_ratings']} ratings • 📊 Score: {row['weighted_score']:.3f}
                            </div>
                        </div>
                    """, unsafe_allow_html=True)
                
                st.success(f"✅ Found {len(recommendations)} amazing movies for you!")
                
            except Exception as e:
                st.error(f"❌ Error getting recommendations: {e}")

def show_similar_movies_page():
    """Similar movies page"""
    
    st.markdown("## 🔍 Find Similar Movies")
    
    if not st.session_state.models_loaded:
        st.warning("⚠️ Please load models first using the sidebar button.")
        return
    
    if not st.session_state.data_loaded:
        st.warning("⚠️ Please load data first using the sidebar button.")
        return
    
    if st.session_state.content_model is None:
        st.error("❌ Content-based model not available.")
        return
    
    st.markdown("""
    <div class="info-box">
        Search for a movie and discover similar titles based on content features like genres, 
        release year, and ratings patterns. Perfect for finding your next favorite! 🎬
    </div>
    """, unsafe_allow_html=True)
    
    # Search input
    col1, col2 = st.columns([3, 1])
    
    with col1:
        search_query = st.text_input("🔎 Search for a movie", placeholder="e.g., Toy Story, Inception, The Matrix...")
    
    with col2:
        num_similar = st.slider("📊 Number of similar movies", 5, 20, 10)
    
    if search_query:
        with st.spinner('🔍 Searching for movies...'):
            # Search for movies matching the query
            matching_movies = st.session_state.movies_df[
                st.session_state.movies_df['title'].str.contains(search_query, case=False, na=False)
            ]
            
            if len(matching_movies) == 0:
                st.warning(f"⚠️ No movies found matching '{search_query}'")
            elif len(matching_movies) == 1:
                movie_id = matching_movies.iloc[0]['movieId']
                movie_title = matching_movies.iloc[0]['title']
                
                try:
                    st.success(f"✅ Finding movies similar to: **{movie_title}**")
                    
                    # Find similar movies
                    similar_movies = st.session_state.content_model.find_similar_movies(movie_id, n=num_similar)
                    
                    st.markdown(f"### 🎬 Movies Similar to: {movie_title}")
                    
                    for idx, row in similar_movies.iterrows():
                        st.markdown(f"""
                            <div class="movie-card">
                                <div class="movie-title">#{idx+1}. {row['title']}</div>
                                <div class="movie-genre">🎭 {row['genres']}</div>
                                <div style="color: #8b5cf6; font-size: 0.9rem; margin-top: 0.5rem;">
                                    📅 Year: {row.get('release_year', 'N/A')}
                                </div>
                            </div>
                        """, unsafe_allow_html=True)
                except Exception as e:
                    st.error(f"❌ Error finding similar movies: {e}")
            else:
                st.info(f"🎯 Found {len(matching_movies)} movies. Please select one:")
                
                # Display matching movies for selection
                for idx, row in matching_movies.head(10).iterrows():
                    col1, col2 = st.columns([4, 1])
                    with col1:
                        st.markdown(f"""
                            <div class="movie-card">
                                <div class="movie-title">{row['title']}</div>
                                <div class="movie-genre">🎭 {row['genres']}</div>
                            </div>
                        """, unsafe_allow_html=True)
                    with col2:
                        if st.button(f"Select", key=f"select_{row['movieId']}"):
                            try:
                                movie_title = row['title']
                                st.success(f"✅ Finding movies similar to: **{movie_title}**")
                                
                                similar_movies = st.session_state.content_model.find_similar_movies(
                                    row['movieId'], n=num_similar
                                )
                                
                                st.markdown(f"### 🎬 Movies Similar to: {movie_title}")
                                
                                for idx2, row2 in similar_movies.iterrows():
                                    st.markdown(f"""
                                        <div class="movie-card">
                                            <div class="movie-title">#{idx2+1}. {row2['title']}</div>
                                            <div class="movie-genre">🎭 {row2['genres']}</div>
                                            <div style="color: #8b5cf6; font-size: 0.9rem; margin-top: 0.5rem;">
                                                📅 Year: {row2.get('release_year', 'N/A')}
                                            </div>
                                        </div>
                                    """, unsafe_allow_html=True)
                            except Exception as e:
                                st.error(f"❌ Error finding similar movies: {e}")

def show_insights_page():
    """Business insights page"""
    
    st.markdown("## 📊 Business Intelligence Dashboard")
    
    if not st.session_state.data_loaded:
        st.warning("⚠️ Please load data first using the sidebar button.")
        st.info("💡 The notebook generates comprehensive insights. This page shows key metrics.")
        return
    
    # Tabs for different insights
    tab1, tab2, tab3, tab4 = st.tabs(["📈 Overview", "👥 User Behavior", "🎬 Content Performance", "💎 Hidden Gems"])
    
    with tab1:
        st.markdown("### 📊 Executive Summary")
        
        # Try to load executive summary
        try:
            if os.path.exists('outputs/executive_summary.json'):
                import json
                with open('outputs/executive_summary.json', 'r') as f:
                    summary = json.load(f)
                
                col1, col2, col3, col4 = st.columns(4)
                
                with col1:
                    st.metric("📊 Total Ratings", summary.get('total_ratings', 'N/A'))
                with col2:
                    st.metric("👥 Active Users", summary.get('unique_users', 'N/A'))
                with col3:
                    st.metric("⭐ Platform Rating", summary.get('avg_rating', 'N/A'))
                with col4:
                    st.metric("🏆 Best Model", summary.get('best_model', 'N/A'))
                
                st.markdown("---")
                st.markdown("""
                <div class="info-box">
                    <strong>🔑 Key Insights:</strong>
                    <ul>
                        <li>📊 User engagement metrics from comprehensive analysis</li>
                        <li>🎭 Genre performance data available in notebook</li>
                        <li>📈 Temporal trends analyzed in detail</li>
                        <li>⭐ Power users identified for targeted strategies</li>
                    </ul>
                </div>
                """, unsafe_allow_html=True)
            else:
                st.info("💡 Run the notebook to generate executive summary. Check outputs/executive_summary.json")
        except Exception as e:
            st.warning(f"⚠️ Could not load executive summary: {e}")
    
    with tab2:
        st.markdown("### 👥 User Segmentation")
        st.markdown("Analysis of user behavior patterns and engagement levels.")
        st.info("📊 Detailed user segmentation analysis is available in the notebook (Part 4).")
        st.markdown("""
        **🎯 Key Segments Identified:**
        - ⭐ Power Users (100+ ratings)
        - 🎬 Active Users (20-100 ratings)
        - 👤 Casual Users (<20 ratings)
        - 😊 Generous vs 😐 Critical Raters
        """)
    
    with tab3:
        st.markdown("### 🎬 Genre Performance")
        st.markdown("Comprehensive analysis of genre ratings and popularity.")
        st.info("📊 Detailed genre performance analysis with engagement scores is available in the notebook (Part 4).")
        st.markdown("""
        **📈 Analysis Includes:**
        - ⭐ Average rating by genre
        - 📊 Total ratings per genre
        - 🎯 Engagement scores
        - ⚖️ Risk vs reward assessment
        """)
    
    with tab4:
        st.markdown("### 💎 Hidden Gems Discovery")
        st.markdown("High-rated movies with low visibility - perfect for recommendations.")
        
        if st.session_state.hidden_gems is not None and not st.session_state.hidden_gems.empty:
            st.dataframe(
                st.session_state.hidden_gems.head(20)[['title', 'genres', 'avg_rating', 'num_ratings', 'gem_score']],
                use_container_width=True
            )
        else:
            st.info("💡 Run the notebook to generate hidden gems data. Check outputs/hidden_gems.csv")

def show_model_performance_page():
    """Model performance comparison page"""
    
    st.markdown("## 📈 Model Performance Comparison")
    
    st.markdown("""
    <div class="info-box">
        🎯 Comparison of different content-based recommendation models trained in the notebook.
    </div>
    """, unsafe_allow_html=True)
    
    # Try to load model comparison
    try:
        if os.path.exists('outputs/model_comparison.csv'):
            comparison_df = pd.read_csv('outputs/model_comparison.csv')
            
            st.markdown("### 📊 Performance Metrics")
            
            col1, col2, col3 = st.columns(3)
            
            with col1:
                best_model = comparison_df.loc[comparison_df['RMSE'].idxmin()]
                st.markdown("#### 🏆 Best Model: " + best_model['Model'])
                st.metric("RMSE", f"{best_model['RMSE']:.4f}", "Lower is better")
                st.metric("MAE", f"{best_model['MAE']:.4f}", "Lower is better")
                st.metric("Accuracy", f"{best_model['Accuracy']:.2%}", "Higher is better")
                st.success("✅ Recommended for Production")
            
            with col2:
                if len(comparison_df) > 1:
                    second = comparison_df.nsmallest(2, 'RMSE').iloc[1]
                    st.markdown("#### 🥈 " + second['Model'])
                    st.metric("RMSE", f"{second['RMSE']:.4f}")
                    st.metric("MAE", f"{second['MAE']:.4f}")
                    st.metric("Accuracy", f"{second['Accuracy']:.2%}")
                    st.info("⚡ Fast Training")
            
            with col3:
                if len(comparison_df) > 2:
                    third = comparison_df.nlargest(1, 'RMSE').iloc[0]
                    st.markdown("#### 🥉 " + third['Model'])
                    st.metric("RMSE", f"{third['RMSE']:.4f}")
                    st.metric("MAE", f"{third['MAE']:.4f}")
                    st.metric("Accuracy", f"{third['Accuracy']:.2%}")
                    st.warning("📊 Baseline Model")
            
            st.markdown("---")
            st.markdown("### 📋 Detailed Comparison")
            st.dataframe(comparison_df, use_container_width=True)
            
            st.markdown("---")
            st.markdown("### 💡 Model Recommendations")
            st.markdown("""
            **Based on comprehensive evaluation:**
            
            1. **🌲 Random Forest** - Best for production deployment
               - ✅ Highest accuracy and lowest error rates
               - ⚖️ Good balance between performance and training time
               - 🛡️ Robust to overfitting with proper tuning
            
            2. **📈 Ridge Regression** - Best for rapid iteration
               - ⚡ Fastest training time
               - ✅ Acceptable performance for most use cases
               - 📊 Easy to interpret and maintain
            
            3. **🔍 KNN** - Baseline comparison
               - ✨ Simple implementation
               - 🎯 Useful for similarity-based recommendations
               - ⏱️ Can be slow with large datasets
            """)
        else:
            st.info("💡 Run the notebook to generate model comparison. Check outputs/model_comparison.csv")
            st.markdown("""
            **📊 Expected Models:**
            - 🌲 Random Forest (Best Performance)
            - 📈 Ridge Regression (Fast Training)
            - 🔍 K-Nearest Neighbors (Baseline)
            """)
    except Exception as e:
        st.error(f"❌ Error loading model comparison: {e}")

if __name__ == "__main__":
    main()